<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>Jellyfin.Plugin.UnifiedLibrary</RootNamespace>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Jellyfin.Controller" Version="10.11.*">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Jellyfin.Model" Version="10.11.*">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<None Remove="Configuration\configPage.html" />
		<None Remove="Web\unifiedPage.html" />
		<EmbeddedResource Include="Configuration\configPage.html" />
		<EmbeddedResource Include="Web\unifiedPage.html" />
	</ItemGroup>

	<!-- Копирование внешнего HTML в папку релиза рядом с DLL -->
	<ItemGroup>
		<None Include="Web\unifiedPage.external.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>unifiedPage.external.html</Link>
		</None>
	</ItemGroup>

</Project>